### ISSUE TITLE
[Questions] Object Backend

### ISSUE THREAD

**Issue by tthiery** [mikhail-barg/jsonata.net.native#10]
We are experimenting right now with jsonata and we have the following issue: we use jsonata in a web page asset to calculate something. We throw in there a json/object tree and get our outcome. Within our backend code we want to evaluate the same jsonata but we have already deserialized the json into a .NET object tree for other purposes.

Do we have already a backend against a object tree and if not, would there be a reason why this could not be implemented similar to the Newtonsoft and System.Text.Json backend?

As a second question: considering the current Newtonsoft and System.Text.Json backend create a internal shadow structure (.Json subtree) and you could have gigantic input trees ... is it realistic to implement the navigational construct without too much duplicate heap allocations?

**Comment by mikhail-barg** [comment]
Hi!

1. That's an interesting idea. If I get you right, you want to query some C# object tree (via reflection) with JSONata queries, correct? This looks possible, but there's a caveat. What do you expect as a result — just a JSON string (as with other "backends") or you expect to receive same C# objects, extracted or constructed from original data?

Former option should be possible, and I'd like to try implementing it (probably by building a parallel `JToken` shadow image for original object tree). And latter seems to be rather complicated with some open questions like "what class to use for newly created objects", etc.


2. If you are asking about streaming implementation, i.e. processing JSONata query over streaming JSON parser, without storing whole tree in memory, it seems rather complicated, and in general would require re-writing whole query processing. I'm not sure if I would be able to implement this in a foreseeable future.

**Comment by mikhail-barg** [comment]
@tthiery I've had a look through the code, and found that we already have a way to build a JToken tree from plain C# object. Please check `JToken.FromObject()` from `Jsonata.Net.Native.Json` namespace

**Comment by tthiery** [comment]
Hi @mikhail-barg 

sorry for late response. That is nice to hear that we already have an implementation for the object-tree to JToken world. Have to try it how it works for us.

Regards the second question: Completely understood. No worries.

**Comment by mikhail-barg** [comment]
closing this for now. Please feel free to reopen in case there's something else to do about it.
