### ISSUE TITLE
Filter with current context item

### ISSUE THREAD

**Issue by sureshssb07** [mikhail-barg/jsonata.net.native#16]
Hi Team, Could you please help me with below query

**Data :**
{
  "my-Array": [
    "red",
    "blue",
    "green",
    "pink"
  ]
}

**Query :**
\'my-Array\'[$ != "pink"]

**Actual Output:** 
** no match **

**Expected Output:**
[
  "red",
  "blue",
  "green"
]

**Comment by mikhail-barg** [comment]
Hi, will look into it a bit later today

**Comment by mikhail-barg** [comment]
@sureshssb07 hi, I've just checked your query, and it does seem to work both in the [original jsonata-js excersiser](https://try.jsonata.org/RgEqX61Lz) and in my C# version:

![image](https://github.com/mikhail-barg/jsonata.net.native/assets/2208971/fe3d8be3-21ca-4ff7-86c8-6cd118f085f9)

**Comment by mikhail-barg** [comment]
The only change I've made to your query was to change straight single quotes (`'`) around `my-Array` into backticks ` `` `, so not 
```
'my-Array'[$ != "pink"]
```

but 

```
`my-Array`[$ != "pink"]
```

because straight quotes make a string, and backticks are for field names.

**Comment by sureshssb07** [comment]
@mikhail-barg Thanks for your quick reply and assistance :)  now I got it., but only thing is when we deep into the child node we used single quote (') . Hereafter will use backticks and both are working for traverse to the child but not able to apply condition with single quote and the same is working with backtick (`). 

Awesome & Great help :)
