### ISSUE TITLE
$fromMillis is not working as expected in C#

### ISSUE THREAD

**Issue by sureshssb07** [mikhail-barg/jsonata.net.native#17]
$fromMillis is not working as expected in C#

Code:
var jsonQ = "$toMillis('10/12/2018', '[D]/[M]/[Y]') ~> $fromMillis('[M]/[D]/[Y]')"; /**/ It is mentioned in Date/Time processing as example**
var jsonQuery = new JsonataQuery(jsonQ);
var jsonValue = jsonQuery.Eval(jsonData);
return jsonValue;

**Exception :** D3136 : Failed to parse tdate/time from '10/12/2018'

But above example is working in JSONata Exerciser tool

And We tried with alternate approach with the format $toMillis('10/12/2018', 'dd/MM/yyyy') ~> $fromMillis('dd/MM/yyyy'). Parse is success but we are getting incorrect date in $fromMillis method "09/12/2018"

**Comment by mikhail-barg** [comment]
Hi @sureshssb07, thanks for reporting this. 

For the part where you try original jsonata-js "picture" (format) strings like `'[D]/[M]/[Y]'` it is expected not to work. As mentioned in [readme](https://github.com/mikhail-barg/jsonata.net.native#function-library), my implementation uses 

> C# [custom](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) and [standard](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings) format strings for picture argument instead of [XPath format](https://docs.jsonata.org/date-time-functions#tomillis) used in JSonataJS

But the second thing where `$toMillis('10/12/2018', 'dd/MM/yyyy') ~> $fromMillis('dd/MM/yyyy')` does not give original date, it surely a bug.

I've found a reason for this behavior (using local time when parsing date with `toMillis()`), and I will get to release a fix soon.

**Comment by mikhail-barg** [comment]
Just released v2.4.1 with a fix. Will close this for now. Please feel free to re-open the issue, if the fix does not help.
