### ISSUE TITLE
Thanks for the project & employees.json for the BenchmarkApp

### ISSUE THREAD

**Issue by mikoskinen** [mikhail-barg/jsonata.net.native#2]
Big thanks for the project, this is much needed!

Regarding the BenchmarkApp, cloning this repo and then trying to build the project doesn't seem to work as it tries to include employees.json from the jsonata-js -folder:

```
  <ItemGroup>
    <Content Include="..\..\jsonata-js\test\test-suite\datasets\employees.json" Link="employees.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```
Is it OK if the file is just copied to this project or is the idea to keep employees.json sync between between the two different repositories?

**Comment by mikhail-barg** [comment]
Hi, thanks for the interest in the project!

Regarding the issue with the employees.json, please note that original jsonata-js is included in this repo as a git sub-module, so to get it contents you'll need to not just `git clone`  jsonata.net.native repo, but also include submodules (which is not done by default :/ ). So you either do a `git clone --recurse-submodules https://github.com/mikhail-barg/jsonata.net.native.git` for a fresh checkout, or `git git submodule update --init --recursive` if you already have cloned the repo. 

This should give you the `jsonata-js` folder with all the content of original repo at the root of `jsonata.net.native`. Please \tell me if this helps or there are other problems.
