### ISSUE TITLE
How to handle undefined value

### ISSUE THREAD

**Issue by sureshssb07** [mikhail-barg/jsonata.net.native#20]
Hi,

We want to handle undefined value in final response. 

Ex:
{
"One": 1,
 "Two": 2
}

Query :  
(
    $finalOut := function($v)
    {
        $v = undefined ? 0 : $v
    };
    $finalOut(`Three`);
)

Actual output : undefined
Expected output : if it is undefined then final value needs to modify

We have tried $lookup(object, key) also but not working 

Thanks in advance :)

**Comment by mikhail-barg** [comment]
Well, this looks like a general Jsonata language question, and I myself is not a pro with it :)

I think it has to do something with `$exists()` function but at the moment I cannot invent a fully working function that would do what I think you expect.

So I'd suggets you ask a question on StackOverflow with [[Jsonata] tag](https://stackoverflow.com/questions/tagged/jsonata). I saw those are answered rather fast.

**Comment by sureshssb07** [comment]
Yeah !!! Thanks for your reply .. will check  in mentioned forum :)
