### ISSUE TITLE
Query Related to Performance

### ISSUE THREAD

**Issue by sureshssb07** [mikhail-barg/jsonata.net.native#23]
Hi @mikhail-barg,

Is there any advantage of creating each object path as local variable like below or is there any provision for executing queries in parallel with the same json data.

EX:
(
    **$order := `Account`.`Order`;** -> Creating path as a local variable (Common Path Declaration) for fetching data for different Json Element like SumOfProduct, ProductName etc.
    {
        "SumOfProduct" : $sum($order.Product.(Price * Quantity)),
        "ProductName" : $order.Product.`Product Name`
    }
) 
Hint : We did small analysis on the code side and found each json elements are referred as a pairs . So we we are looking for executing in parallel

Thanks in Advance :)

**Comment by mikhail-barg** [comment]
hi @sureshssb07 ! 

Frankly speaking, I have a hard time understanding your case, especially the "parallel" part.

Could you please give more details on what you are doing and expecting to achieve?

**Comment by mikhail-barg** [comment]
Still, as a wild guess, in case you are asking if it's ok to run two queries on a single source json in parallel, that should work just fine, because a query itself does not modify source data during execution.

(At least that was a case before the "parent" feature was introduced)

**Comment by sureshssb07** [comment]
@mikhail-barg Sorry for Delay. Actually we are using 5MB Json data and executing group functionality with $$ . So when we are executing query its taking 10-12 mins and then we removed $$ and running same and it is giving result 15millisecond. So we identified the issue in $$ and changed the query and it is giving quick result. Thanks for your quick reply and wonderful support.

If Possible could you please share some C# snippet for executing queries in parallel with single data source. Thanks in advance.
