### ISSUE TITLE
Unexpected Behavior in Debug Mode with Parent (%) operator

### ISSUE THREAD

**Issue by TheMies** [mikhail-barg/jsonata.net.native#25]
Hello,

I encountered an unexpected issue related to the parent operator while using the Jsonata library. Initially, I tested the parent operator in a Release build of the Jsonata Exerciser, and it functioned correctly.

However, when I executed the same query with identical JSON data in Debug mode within my code, the library terminated without any thrown exceptions. Subsequently, I attempted to replicate the behavior using the Debug version of the Jsonata Exerciser, which resulted in the same abnormal behavior.

Switching the execution mode of my code to Release resolved the issue successfully. :)

Here's is what I did to reproduce it:

Query:
```
(
    $parents := $[type = "parent"];
    
    $getNames := function($p){
        $parents.values[$p in $keys()].%.name
    };

    $data := $[type = "child"].{
        "id": id,
        "allParentNames":$getNames(parentProperty),
    };
)
```

Input:
```json
[
  {
    "type": "parent",
    "id": 1,
    "name": "name1",
    "values": {
      "param1": "param1data"
    }
  },
  {
    "type": "parent",
    "id": 2,
    "name": "name2",
    "values": {
      "param2": "param2data"
    }
  },
  {
    "type": "parent",
    "id": 3,
    "name": "name3",
    "values": {
      "param1": "param1data"
    }
  },
  {
    "type": "child",
    "id": 10,
    "name": "child1",
    "parentProperty": "param1"
  }
]
```

**Comment by mikhail-barg** [comment]
Hi @TheMies I've tried to reproduce the effect you are describing using the data and query you provided, but everything seem to work fine on my side:

![image](https://github.com/mikhail-barg/jsonata.net.native/assets/2208971/a9c5d51b-99ca-41a4-912f-6e68462e393d)

**Comment by mikhail-barg** [comment]
All that I can suggest at the moment, is that you try get more info while reproducing the problem on your side.

E.g., does the issue happens when you run code in IDE? If yes, then maybe you can get more info from IDE, eg. from output window? Or via debugging the library code with "just my code" option disabled?

Or, if it happens when running the program binary, then maybe you could get more info from system facilities? Like Windows "event viewer", or similar Linux tools?

**Comment by TheMies** [comment]
After an update of your repo, I could not reproduce the issue anymore. Seems I got behind with the updates... :| 
Thanks for testing and feedback, though! Great package!
