### ISSUE TITLE
.NET NuGet package sign with strong key

### ISSUE THREAD

**Issue by romanrotter** [mikhail-barg/jsonata.net.native#5]
Hello,

is it possible to sign this library published as NuGet with a strong key so that it's possible to use it in applications which requires it?

Thanks and regards,
Roman

**Comment by mikhail-barg** [comment]
Hi, sorry for a late answer. Will look into this.

**Comment by mikhail-barg** [comment]
Hi Roman, could you please elaborate on your need to sign the assemblies?
I'm reading the MS [docs](https://docs.microsoft.com/en-us/dotnet/standard/assembly/create-use-strong-named) which say:
> Although .NET Core supports strong-named assemblies, and all assemblies in the .NET Core library are signed, the majority of third-party assemblies do not need strong names. For more information, see [Strong Name Signing](https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md) on GitHub.

And then, following the link:
> This is extremely problematic for libraries, such as Json.NET, which have large incoming dependencies.

So are you using the lib in some sandboxed environment like COM?

**Comment by romanrotter** [comment]
Hi, 

no, it's internal desktop app on .net 4.8 published with ClickOnce. If it's unsigned then it never pass through defender and it's blocked without ask on our computers before run. Also using unsigned libraries doesn't comply to our internal policies.

I saw that some authors who wanted to keep using unsigned dll publish in parallel signed nuget with .Signed suffix in name so that people can chose. 

But we'll check how it's working with .net 6 where we are planning to migrate, based on links which you sent it seems that it's not needed. Actually .net 4.8 signed app cannot use unsigned libraries, it crash on the first call.

Roman

**Comment by mikhail-barg** [comment]
Hi, thanks for the explanation. I've just released a v2.0.0 of package, and signed it with a strong name. Hope this would help you.

Please note that there's a breaking change in this release (switching to custom JSON parser and moving JSON.Net binding to another package). The details of the change could be seen here: https://github.com/mikhail-barg/jsonata.net.native/commit/69617d23026104b46433e20f2da286cf50cfd519

**Comment by romanrotter** [comment]
Thank you very much :)
