### ISSUE TITLE
Not escaping double quotes correctly

### ISSUE THREAD

**Issue by kreadyf** [mikhail-barg/jsonata.net.native#7]
Method's which are converting Jsonata.Net.Native.Json.JToken to another format / string, like

.ToFlatString()
.ToIndentedString()

or also .ToSystemTextJson() etc.

are not escaping double quotes.

Example code:
JToken evaluated = new JsonataQuery("*").Eval(JToken.Parse("{\"obj\":{\"myText\":\"Lorem \\\"ipsum\\\"\"}}"));
       
string str = evaluated.ToIndentedString(); // json does not have escaped double quotes
            
JsonSerializer.Deserialize(str); // Parser Exception
            
evaluated.ToSystemTextJson(); // Parser Exception

**Comment by mikhail-barg** [comment]
Just released a [2.0.1](https://github.com/mikhail-barg/jsonata.net.native/releases/tag/v2.0.1) bugfix release.
Thanks again for reporting this!

**Comment by kreadyf** [comment]
Hey there, thanks to YOU for fixing this so fast 😊


Florian Dürrbaum
Dipl.-Ing. Inf. FH

| kreadyf S.R.L.
| www.kreadyf.com<http://www.kreadyf.com/>

[7ABBBAA9]
