### ISSUE TITLE
$fromMillis() returning unexpected format

### ISSUE THREAD

**Issue by LennertS** [mikhail-barg/jsonata.net.native#8]
In v2.0.1 I'm trying the following query, which I would expect to return "1970-01-01" (see JSONata exerciser https://try.jsonata.org/i0rWiz5_U).

JsonataQuery query = new JsonataQuery("$fromMillis(1, '[Y0001]-[M01]-[D01]')"); 
var translatedObject = query.Eval("{}"); //evaluates as "[Y0001]-[101]-[D01]"

JSONata.Net evaluates the query as "[Y0001]-[101]-[D01]".

Am I missing something here?

Kind regards.

**Comment by mikhail-barg** [comment]
Hi, thanks for the interest in the project!

As mentioned in the [readme](https://github.com/mikhail-barg/jsonata.net.native/blob/master/README.md):
> ✔️ Implemented: $now(), $millis(), $fromMillis(), $toMillis()
> ✅ Using C# [custom](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) and [standard](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings) format strings for picture argument instead of [XPath format](https://docs.jsonata.org/date-time-functions#tomillis) used in JSONataJS.

I've found that it would be too time-consuming to properly implement XPath date/time formatter from scratch and I've found no reusable .net implementations for it. So instead I've decided to use C# built-in formatting capabilities.

So, in your case it would be `$fromMillis(1, 'yyyy-MM-dd')`

![image](https://user-images.githubusercontent.com/2208971/223506992-d9d6720a-adba-4cc1-b793-7cb7c91db743.png)

**Comment by LennertS** [comment]
Great! Thanks for the quick reply and effort on this project.
It has been most helpful!
